# Generated by Django 4.2.7 on 2025-08-05 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='flashcards.flashcard'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='flashcards', to='flashcards.tag'),
        ),
        migrations.AddField(
            model_name='dailycard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.flashcard'),
        ),
        migrations.AddField(
            model_name='cardusagelog',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.flashcard'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['title'], name='flashcards__title_e9edee_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['is_active'], name='flashcards__is_acti_9f96ea_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['created_at'], name='flashcards__created_43dd56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cardusagelog',
            unique_together={('card', 'used_date', 'cycle_number')},
        ),
    ]
