# Generated by Django 4.2.7 on 2025-11-15 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='version',
            new_name='version_number',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='parent_version',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='is_live',
            field=models.BooleanField(db_index=True, default=True, help_text='Only one version per group should be live'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='version_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Groups all versions of the same card'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['version_group', 'is_live'], name='flashcards__version_af0ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['version_group', '-version_number'], name='flashcards__version_ef679b_idx'),
        ),
    ]
