# Generated by Django 4.2.7 on 2026-09-11 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0006_flashcard_short_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
