# Generated by Django 4.2.7 on 2026-09-13 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0007_alter_flashcard_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look_and_feel', models.TextField(blank=True, default='Serene minimalist illustration, soft natural light, warm muted earth tones, hand-painted texture, calm and contemplative mood, generous negative space.', help_text='Style guidance appended to every prompt. Overridable per image.')),
                ('model', models.CharField(default='black-forest-labs/flux.2-pro', help_text='OpenRouter model slug used for new generations.', max_length=200)),
                ('enabled', models.BooleanField(default=True, help_text='Master switch. When off, the bot generates nothing.')),
                ('auto_generate_new_cards', models.BooleanField(default=True, help_text='Queue an image automatically the first time a card is seen.')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, help_text='Hard cap on generation attempts per image row, so a failing card cannot loop forever.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image generation settings',
                'verbose_name_plural': 'Image generation settings',
            },
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_group', models.UUIDField(db_index=True, help_text='The card family this image belongs to; survives card edits.')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='card_images/generated/')),
                ('prompt', models.TextField(help_text='The full prompt sent to the model, look and feel included.')),
                ('prompt_seed', models.TextField(blank=True, help_text='The card-derived portion of the prompt, before style guidance.')),
                ('look_and_feel', models.TextField(blank=True, help_text='The style guidance actually used, snapshotted at generation time.')),
                ('look_and_feel_override', models.TextField(blank=True, help_text='Per-image style guidance. When set, it replaces the global look and feel.')),
                ('model', models.CharField(max_length=200)),
                ('is_accepted', models.BooleanField(db_index=True, default=False, help_text='Only an accepted image is visible outside the admin area.')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('provider_response_id', models.CharField(blank=True, max_length=200)),
                ('is_auto', models.BooleanField(default=False, help_text='True when queued by the bot rather than by an admin.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(blank=True, help_text='The card version whose text seeded the prompt. Kept for provenance only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_images', to='flashcards.flashcard')),
                ('requested_by', models.ForeignKey(blank=True, help_text='Null when the bot queued it automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_card_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['version_group', '-created_at'], name='flashcards__version_69032d_idx'), models.Index(fields=['version_group', 'is_accepted'], name='flashcards__version_aa3b7f_idx'), models.Index(fields=['status', 'created_at'], name='flashcards__status_984203_idx')],
            },
        ),
    ]
