# Generated by Django 4.2.7 on 2026-09-13 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0008_imagegenerationsettings_cardimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardImagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_group', models.UUIDField(db_index=True, help_text='The card family these preferences apply to.', unique=True)),
                ('model', models.CharField(blank=True, default='', help_text='OpenRouter model slug for this card. Blank uses the global default.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card image preference',
                'verbose_name_plural': 'Card image preferences',
            },
        ),
    ]
