# Generated by Django 4.2.7 on 2026-09-15 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0009_cardimagepreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('studio', 'Studio - light, editorial, quiet'), ('dusk', 'Dusk - dark, luminous, still'), ('clay', 'Clay - warm, organic, tactile'), ('neon', 'Neon - the original psychedelic')], default='studio', help_text='The theme every visitor sees. Takes effect on their next page load. Must stay in step with THEMES in frontend/src/composables/useTheme.js.', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
