# Generated by Django 4.2.7 on 2026-09-16 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0011_media_pointer'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime number of times this card has been favourited. Never decremented.'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_group', models.UUIDField(db_index=True, help_text='The card family favourited; survives card edits.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text="Cascades: a removed user's favourites are theirs alone and carry no history worth keeping.", on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='flashcards__user_id_829ca9_idx')],
                'unique_together': {('user', 'version_group')},
            },
        ),
    ]
