# Generated by Django 4.2.7 on 2026-09-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_cards',
        ),
    ]
